message(STATUS "include WindowsPC-MSVC")

set(BUILD_CPU_ARCHITECTURE x64)
set(BUILD_PLATFORM MinGW64)
set(WINDOWS TRUE)

set(OUTPUT_DIRECTORY_NAME "win_x64")

include ("${CMAKE_CURRENT_LIST_DIR}/../../CRYENGINE-MSVC.cmake")