name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install wget
      run: |
        choco install wget --no-progress
        
    - name: Prepare Sonar scanner
      run: |
        echo "$PATH"
        wget -nv https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.1.2450-windows.zip
        unzip -q sonar-scanner-cli-4.6.1.2450-windows.zip
        echo "${PWD}/sonar-scanner-cli-4.6.1.2450-windows/bin/" >> $GITHUB_PATH
        wget -nv https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
        unzip -q build-wrapper-win-x86.zip          
        echo "${PWD}/build-wrapper-win-x86" >> $GITHUB_PATH
        echo "$PATH"
        pwd
        ls -l .
         
    - name: install vcpkg
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        ./vcpkg.exe integrate install
        .\vcpkg.exe install ms-gsl
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: echo MSBuild
      run: msbuild -version
          
    - name: Compile
      run: |
        pwd
        ls -l .
        ./build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir bw-outputs MSBuild.exe ConsoleGame.sln /t:Rebuild

    - name: check path
      run: |
        echo "$PATH"
        pwd
        ls -l .
        
    - name: SonarCloud Scan
      run: |
        pwd
        ls -l .
        ./sonar-scanner-cli-4.6.1.2450-windows/bin/sonar-scanner.bat -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=romantsovs -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
    - uses: actions/upload-artifact@v2
      with:
        name: ConsoleGame
        path: ./build\Win32\Debug\ConsoleGame.exe
