name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: install vcpkg
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        ./vcpkg.exe integrate install
        .\vcpkg.exe install ms-gsl
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: echo MSBuild
      run: msbuild -version
      
    - name: MSBuild
      run: |
          msbuild $Env:GITHUB_WORKSPACE\ConsoleGame.sln
          echo "Root Directory"
          ls -l .
          cd build
          ls -l .
          
    - uses: actions/upload-artifact@v2
      with:
        name: ConsoleGame
        path: ./build\Win32\Debug\ConsoleGame.exe
