name: Build CMake Project with GCC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose other runners like 'ubuntu-22.04' or 'ubuntu-20.04'

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up GCC
      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++

      # Set up CMake
      - name: Set up CMake
        run: |
          sudo apt-get install -y cmake

      # Install Boost libraries
      - name: Install Boost
        run: |
          sudo apt-get install -y libboost-all-dev

      # Create build directory
      - name: Create build directory
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      # Build the project using GCC
      - name: Build with CMake
        run: |
          cd build
          cmake --build . -- -j$(nproc)
